EncryptedString Project: Iterator Class Reference
Iterator Class Reference
Iterátor az EncryptedString bejárásához.
#include <iterator.h>
Public Member Functions
Iterator (const EncryptedString *owner, unsigned int index)
Konstruktor.
char operator* () const
Dereferálás.
Iterator & operator++ ()
Prefix növelés.
bool operator!= (const Iterator &rhs) const
Összehasonlítás.
Private Attributes
const EncryptedString * owner
Tulajdonos string.
unsigned int index
Aktuális pozíció
Detailed Description
Iterátor az EncryptedString bejárásához.
A dekódolt karaktereken iterál végig.
Definition at line 17 of file iterator.h.
Constructor & Destructor Documentation
Iterator()
Iterator::Iterator (const EncryptedString * owner, unsigned int index)
Konstruktor.
Parameters
owner A string, amin iterálunk.
index Kezdő index.
References index, and owner.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
bool Iterator::operator!= (const Iterator & rhs) const
Összehasonlítás.
References Iterator().
operator*()
char Iterator::operator* () const
Dereferálás.
Returns
Az aktuális karakter (dekódolva).
operator++()
Iterator & Iterator::operator++ ()
Prefix növelés.
Returns
Az iterátor referenciája.
References Iterator().
Member Data Documentation
index
unsigned int Iterator::index private
Aktuális pozíció
Definition at line 20 of file iterator.h.
Referenced by Iterator().
owner
const EncryptedString* Iterator::owner private
Tulajdonos string.
Definition at line 19 of file iterator.h.
Referenced by Iterator().
The documentation for this class was generated from the following file:
iterator.h