EncryptedString Project: EncryptedString Class Reference
EncryptedString Class Reference
Titkosított formában tárolt szöveg.
#include <encrypted_string.h>
Public Member Functions
EncryptedString (const Encryptor &enc)
Konstruktor.
EncryptedString (const char *text, const Encryptor &enc)
Konstruktor C-stringből.
EncryptedString (const EncryptedString &other)
Másoló konstruktor.
~EncryptedString ()
Destruktor.
EncryptedString & operator= (const EncryptedString &other)
Értékadás operátor.
char operator[] (unsigned int index) const
Indexelés.
EncryptedString operator+ (const EncryptedString &rhs) const
Összefűzés.
EncryptedString & operator+= (const EncryptedString &rhs)
Összefűzés és értékadás.
bool operator== (const EncryptedString &rhs) const
Összehasonlítás.
bool operator!= (const EncryptedString &rhs) const
void push_back (char c)
Karakter hozzáadása.
unsigned int size () const
Méret lekérdezése.
void clear ()
String törlése.
Iterator begin () const
Iterátor kezdete.
Iterator end () const
Iterátor vége.
Private Member Functions
void reserve (unsigned int newCap)
Private Attributes
char * data
Titkosított karakterek.
unsigned int length
Aktuális hossz.
unsigned int capacity
Kapacitás.
const Encryptor * enc
Titkosítási algoritmus.
Detailed Description
Titkosított formában tárolt szöveg.
A karaktereket titkosítva tárolja, de a felhasználó számára dekódolt formában biztosítja az elérést.
Definition at line 19 of file encrypted_string.h.
Constructor & Destructor Documentation
EncryptedString() [1/3]
EncryptedString::EncryptedString (const Encryptor & enc) explicit
Konstruktor.
References enc.
Referenced by EncryptedString(), operator!=(), operator+(), operator+=(), operator=(), and operator==().
EncryptedString() [2/3]
EncryptedString::EncryptedString (const char * text, const Encryptor & enc)
Konstruktor C-stringből.
References enc.
EncryptedString() [3/3]
EncryptedString::EncryptedString (const EncryptedString & other)
Másoló konstruktor.
References EncryptedString().
~EncryptedString()
EncryptedString::~EncryptedString ()
Destruktor.
Member Function Documentation
begin()
Iterator EncryptedString::begin () const
Iterátor kezdete.
clear()
void EncryptedString::clear ()
String törlése.
end()
Iterator EncryptedString::end () const
Iterátor vége.
operator!=()
bool EncryptedString::operator!= (const EncryptedString & rhs) const
References EncryptedString().
operator+()
EncryptedString EncryptedString::operator+ (const EncryptedString & rhs) const
Összefűzés.
References EncryptedString().
operator+=()
EncryptedString & EncryptedString::operator+= (const EncryptedString & rhs)
Összefűzés és értékadás.
References EncryptedString().
operator=()
EncryptedString & EncryptedString::operator= (const EncryptedString & other)
Értékadás operátor.
References EncryptedString().
operator==()
bool EncryptedString::operator== (const EncryptedString & rhs) const
Összehasonlítás.
References EncryptedString().
operator[]()
char EncryptedString::operator[] (unsigned int index) const
Indexelés.
push_back()
void EncryptedString::push_back (char c)
Karakter hozzáadása.
reserve()
void EncryptedString::reserve (unsigned int newCap) private
size()
unsigned int EncryptedString::size () const
Méret lekérdezése.
Member Data Documentation
capacity
unsigned int EncryptedString::capacity private
Kapacitás.
Definition at line 23 of file encrypted_string.h.
data
char* EncryptedString::data private
Titkosított karakterek.
Definition at line 21 of file encrypted_string.h.
enc
const Encryptor* EncryptedString::enc private
Titkosítási algoritmus.
Definition at line 24 of file encrypted_string.h.
Referenced by EncryptedString(), and EncryptedString().
length
unsigned int EncryptedString::length private
Aktuális hossz.
Definition at line 22 of file encrypted_string.h.
The documentation for this class was generated from the following file:
encrypted_string.h